#!/bin/bash

#How to install and configure SonarQube on CentOS 7
#Follow below steps successively to install sonarqube on your centOS server. This process need to be run as a regular user ( Sonarqube doesnt work when you 
start it as root user).


#su - vagrant
#Step 1: Java 11 installation
#The only prerequisite for running SonarQube is to have Java (Oracle JRE 11 or OpenJDK 11) installed on your machine. To install OpenJDK 11, run the following commands


sudo yum update -y

sudo yum install java-11-openjdk-devel -y

sudo yum install java-11-openjdk -y
#Step 2: Download SonarQube latest versions on your server
#Let’s navigate to the /opt directory before downloading


cd /opt
#If wget is not installed on your system, run the command to install it. Then download SonarQube package:


sudo yum install wget -y

sudo wget https://binaries.sonarsource.com/Distribution/sonarqube/sonarqube-9.3.0.51899.zip
#Step 3: Extract packages
#If unzip is not installed on your system, run the command


sudo yum install unzip -y
#To install it. Now, unzip the previously installed package:


sudo unzip /opt/sonarqube-9.3.0.51899.zip
#Step 4: Change ownership to the user and Switch to Linux binaries directory to start service

sudo chown -R vagrant:vagrant /opt/sonarqube-9.3.0.51899

cd /opt
cd sonarqube-9.3.0.51899
cd bin
cd linux-x86-64

pwd
sleep 2

 ./sonar.sh start

#Connect to SonaQube
#Connect to the SonarQube server through the browser. It uses port 9000.

#http://<your-ip-address>:9000

#NB: Some servers have firewall enabled. So if you are not able to connect from the browser, then you might want to open the port 9000 with this command:   

systemctl start firewalld
systemctl enable firewalld

sudo firewall-cmd --permanent --add-port=9000/tcpcd

sudo firewall-cmd --reload